export type ProductAttribute = {
  key: string;
  value: string;
};

export const PRODUCT_ATTRIBUTE_SUGGESTIONS = [
  "material",
  "tecnica",
  "color",
  "estilo",
  "uso",
  "coleccion",
] as const;

export const PRODUCT_ATTRIBUTE_VALUE_SUGGESTIONS: Record<string, string[]> = {
  material: [
    "ceramica",
    "madera",
    "alpaca",
    "cuero",
    "algodon",
    "lino",
    "lana",
    "vidrio",
    "metal",
    "arcilla",
    "papel",
    "carton",
    "hilo",
    "mimbre",
    "ratan",
    "bambu",
    "fibra natural",
    "bronce",
    "acero",
    "plata",
    "cobre",
    "gres",
    "porcelana",
    "resina",
    "fieltro",
    "jean reciclado",
    "tela reciclada",
    "cuero vacuno",
    "cuero vegano",
    "piedra",
  ],
  tecnica: [
    "tejido a mano",
    "ceramica esmaltada",
    "grabado",
    "bordado",
    "macrame",
    "tallado",
    "costura independiente",
    "cesteria",
    "pintado a mano",
    "orfebreria",
    "crochet",
    "dos agujas",
    "telar",
    "fieltro agujado",
    "encuadernacion independiente",
    "vitrofusion",
    "mosaico",
    "torno ceramico",
    "modelado a mano",
    "calado",
    "estampado",
    "serigrafia",
    "sublimado independiente",
    "patchwork",
    "macerado",
    "tintura natural",
    "talla en madera",
    "repujado",
    "alambrismo",
    "ensamble manual",
  ],
  color: [
    "natural",
    "blanco",
    "negro",
    "rojo",
    "azul",
    "verde",
    "amarillo",
    "terracota",
    "multicolor",
    "pastel",
    "gris",
    "beige",
    "marron",
    "arena",
    "crudo",
    "bordo",
    "rosa",
    "fucsia",
    "violeta",
    "lila",
    "turquesa",
    "celeste",
    "azul marino",
    "verde oliva",
    "verde agua",
    "mostaza",
    "naranja",
    "dorado",
    "plateado",
    "cobre",
  ],
  estilo: [
    "rustico",
    "clasico",
    "minimalista",
    "boho",
    "nordico",
    "tradicional",
    "contemporaneo",
    "regional",
    "moderno",
    "elegante",
    "romantico",
    "organico",
    "independiente",
    "folk",
    "etnico",
    "industrial",
    "vintage",
    "campestre",
    "costero",
    "urbano",
    "infantil",
    "festivo",
    "artistico",
  ],
  uso: [
    "decoracion",
    "mesa",
    "cocina",
    "indumentaria",
    "accesorio",
    "regalo",
    "hogar",
    "uso diario",
    "mate",
    "oficina",
    "bano",
    "dormitorio",
    "living",
    "jardin",
    "ceremonia",
    "evento",
    "juego",
    "infancias",
    "organizacion",
    "almacenamiento",
    "iluminacion",
    "pared",
    "mesa navidena",
    "souvenir",
    "autocuidado",
    "accesorio personal",
  ],
  coleccion: [
    "edicion limitada",
    "temporada",
    "linea clasica",
    "nueva coleccion",
    "especial feria",
    "piezas unicas",
    "otoño invierno",
    "primavera verano",
    "capsula",
    "hecho en guemes",
    "coleccion hogar",
    "coleccion mesa",
    "coleccion textil",
    "coleccion ceramica",
    "coleccion regalos",
    "serie botanica",
    "serie geometrica",
    "serie natural",
    "serie color",
    "coleccion autor",
  ],
};

export function getProductAttributeValueSuggestions(attributeKey: string) {
  return PRODUCT_ATTRIBUTE_VALUE_SUGGESTIONS[attributeKey.trim().toLowerCase()] ?? [];
}

export function sanitizeProductAttributes(attributes: ProductAttribute[]) {
  return attributes
    .map((attribute) => ({
      key: attribute.key.trim(),
      value: attribute.value.trim(),
    }))
    .filter((attribute) => attribute.key.length > 0 && attribute.value.length > 0)
    .slice(0, 12);
}
