-- Phase 6 analytics: daily, auditable retention maintenance. This job only
-- deletes analytics-owned rows and never touches profiles, orders or products.

create extension if not exists pg_cron with schema pg_catalog;

create table if not exists public.analytics_maintenance_runs (
  id bigint generated by default as identity primary key,
  job_name text not null default 'analytics-daily-cleanup'
    check (char_length(job_name) between 1 and 80),
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  duration_ms integer check (duration_ms is null or duration_ms >= 0),
  status text not null default 'running' check (status in ('running', 'success', 'failed')),
  deleted_counts jsonb not null default '{}'::jsonb,
  error_message text check (error_message is null or char_length(error_message) <= 500),
  created_at timestamptz not null default now()
);

create index if not exists analytics_maintenance_runs_started_idx
  on public.analytics_maintenance_runs (started_at desc);

alter table public.analytics_maintenance_runs enable row level security;
revoke all on table public.analytics_maintenance_runs from public, anon, authenticated;

create or replace function public.run_internal_analytics_maintenance()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  deleted_anonymous_daily integer := 0;
  deleted_delivery_receipts integer := 0;
  deleted_events integer := 0;
  deleted_maintenance_runs integer := 0;
  deleted_quality_hourly integer := 0;
  deleted_rate_limits integer := 0;
  deleted_sessions integer := 0;
  finished_time timestamptz;
  result jsonb;
  run_id bigint;
  started_time timestamptz := clock_timestamp();
begin
  insert into public.analytics_maintenance_runs (started_at, status)
  values (started_time, 'running')
  returning id into run_id;

  begin
    delete from public.analytics_rate_limits where expires_at <= now();
    get diagnostics deleted_rate_limits = row_count;

    delete from public.analytics_delivery_receipts where expires_at <= now();
    get diagnostics deleted_delivery_receipts = row_count;

    delete from public.analytics_events
    where occurred_at < now() - interval '365 days';
    get diagnostics deleted_events = row_count;

    delete from public.analytics_sessions
    where started_at < now() - interval '365 days';
    get diagnostics deleted_sessions = row_count;

    delete from public.analytics_anonymous_daily
    where bucket_date < current_date - 730;
    get diagnostics deleted_anonymous_daily = row_count;

    delete from public.analytics_anonymous_quality_hourly
    where bucket_hour < now() - interval '730 days';
    get diagnostics deleted_quality_hourly = row_count;

    delete from public.analytics_maintenance_runs
    where started_at < now() - interval '730 days'
      and id <> run_id;
    get diagnostics deleted_maintenance_runs = row_count;

    finished_time := clock_timestamp();
    result := jsonb_build_object(
      'anonymousDaily', deleted_anonymous_daily,
      'deliveryReceipts', deleted_delivery_receipts,
      'events', deleted_events,
      'maintenanceRuns', deleted_maintenance_runs,
      'qualityHourly', deleted_quality_hourly,
      'rateLimits', deleted_rate_limits,
      'sessions', deleted_sessions
    );

    update public.analytics_maintenance_runs
    set
      deleted_counts = result,
      duration_ms = greatest(
        0,
        round(extract(epoch from (finished_time - started_time)) * 1000)::integer
      ),
      finished_at = finished_time,
      status = 'success'
    where id = run_id;

    return jsonb_build_object('runId', run_id, 'status', 'success', 'deleted', result);
  exception when others then
    finished_time := clock_timestamp();
    update public.analytics_maintenance_runs
    set
      duration_ms = greatest(
        0,
        round(extract(epoch from (finished_time - started_time)) * 1000)::integer
      ),
      error_message = left(sqlerrm, 500),
      finished_at = finished_time,
      status = 'failed'
    where id = run_id;

    return jsonb_build_object('runId', run_id, 'status', 'failed');
  end;
end;
$$;

revoke all on function public.run_internal_analytics_maintenance() from public;
grant execute on function public.run_internal_analytics_maintenance() to service_role;

create or replace function public.cleanup_internal_analytics()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.run_internal_analytics_maintenance();
end;
$$;

revoke all on function public.cleanup_internal_analytics() from public;
grant execute on function public.cleanup_internal_analytics() to service_role;

create or replace function public.get_admin_analytics_maintenance_status()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  last_run public.analytics_maintenance_runs;
  last_success_at timestamptz;
begin
  if not public.is_admin() then
    raise exception 'Admin access required.';
  end if;

  select *
  into last_run
  from public.analytics_maintenance_runs
  order by started_at desc
  limit 1;

  select max(finished_at)
  into last_success_at
  from public.analytics_maintenance_runs
  where status = 'success';

  return jsonb_build_object(
    'durationMs', coalesce(last_run.duration_ms, 0),
    'isOverdue', last_success_at is null or last_success_at < now() - interval '36 hours',
    'lastRunAt', last_run.started_at,
    'lastStatus', coalesce(last_run.status, 'missing'),
    'lastSuccessAt', last_success_at,
    'schedule', '03:17 UTC daily'
  );
end;
$$;

revoke all on function public.get_admin_analytics_maintenance_status() from public;
grant execute on function public.get_admin_analytics_maintenance_status() to authenticated;

do $$
declare
  existing_job_id bigint;
begin
  for existing_job_id in
    select jobid from cron.job where jobname = 'analytics-daily-cleanup'
  loop
    perform cron.unschedule(existing_job_id);
  end loop;

  perform cron.schedule(
    'analytics-daily-cleanup',
    '17 3 * * *',
    'select public.run_internal_analytics_maintenance();'
  );
end;
$$;

do $$
declare
  initial_result jsonb;
begin
  initial_result := public.run_internal_analytics_maintenance();
  if initial_result->>'status' <> 'success' then
    raise exception 'Initial analytics maintenance did not complete successfully.';
  end if;
end;
$$;
