-- Internal, privacy-first analytics.
-- Anonymous traffic is stored only as daily aggregates. Detailed sessions and
-- events require an authenticated user with an active consent record.

create table if not exists public.analytics_consents (
  user_id uuid primary key references public.profiles (id) on delete cascade,
  policy_version text not null check (char_length(policy_version) between 1 and 40),
  accepted_at timestamptz not null default now(),
  revoked_at timestamptz,
  updated_at timestamptz not null default now(),
  constraint analytics_consents_dates_check
    check (revoked_at is null or revoked_at >= accepted_at)
);

create table if not exists public.analytics_consent_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles (id) on delete cascade,
  policy_version text not null check (char_length(policy_version) between 1 and 40),
  action text not null check (action in ('accepted', 'revoked')),
  created_at timestamptz not null default now()
);

create table if not exists public.analytics_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles (id) on delete cascade,
  started_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  ended_at timestamptz,
  active_seconds integer not null default 0 check (active_seconds between 0 and 31536000),
  landing_path text not null default '/' check (char_length(landing_path) <= 240),
  referrer_domain text not null default 'direct' check (char_length(referrer_domain) <= 120),
  device_type text not null check (device_type in ('computer', 'mobile', 'tablet', 'other')),
  os_family text not null check (os_family in ('windows', 'macos', 'linux', 'android', 'ios', 'ipados', 'chromeos', 'other')),
  performance_tier text not null check (performance_tier in ('high', 'medium', 'low', 'unknown')),
  classification_confidence text not null check (classification_confidence in ('high', 'medium', 'low')),
  browser_family text not null check (browser_family in ('chrome', 'safari', 'firefox', 'edge', 'opera', 'other')),
  connection_type text not null check (connection_type in ('fast', 'standard', 'slow', 'unknown')),
  screen_size text not null check (screen_size in ('small', 'medium', 'large')),
  country_code text not null default 'unknown' check (char_length(country_code) <= 8),
  region text not null default 'unknown' check (char_length(region) <= 100),
  city text not null default 'unknown' check (char_length(city) <= 100),
  timezone text not null default 'unknown' check (char_length(timezone) <= 80),
  classifier_version text not null check (char_length(classifier_version) <= 30),
  created_at timestamptz not null default now()
);

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.analytics_sessions (id) on delete cascade,
  user_id uuid not null references public.profiles (id) on delete cascade,
  event_name text not null check (event_name in (
    'page_view',
    'product_view',
    'artisan_view',
    'search',
    'filter',
    'contact_click',
    'signup_completed',
    'favorite_add',
    'cart_add',
    'checkout_start',
    'purchase_completed'
  )),
  path text not null default '/' check (char_length(path) <= 240),
  entity_type text check (entity_type is null or entity_type in ('product', 'artisan', 'category', 'checkout')),
  entity_id uuid,
  occurred_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.analytics_anonymous_daily (
  bucket_date date not null default current_date,
  event_name text not null check (event_name in (
    'visit',
    'page_view',
    'product_view',
    'artisan_view',
    'search',
    'filter',
    'contact_click',
    'signup_started'
  )),
  path text not null default '/' check (char_length(path) <= 240),
  device_type text not null check (device_type in ('computer', 'mobile', 'tablet', 'other')),
  os_family text not null check (os_family in ('windows', 'macos', 'linux', 'android', 'ios', 'ipados', 'chromeos', 'other')),
  performance_tier text not null check (performance_tier in ('high', 'medium', 'low', 'unknown')),
  country_code text not null default 'unknown' check (char_length(country_code) <= 8),
  region text not null default 'unknown' check (char_length(region) <= 100),
  city text not null default 'unknown' check (char_length(city) <= 100),
  referrer_domain text not null default 'direct' check (char_length(referrer_domain) <= 120),
  total_count bigint not null default 0 check (total_count >= 0),
  updated_at timestamptz not null default now(),
  primary key (
    bucket_date,
    event_name,
    path,
    device_type,
    os_family,
    performance_tier,
    country_code,
    region,
    city,
    referrer_domain
  )
);

create index if not exists analytics_sessions_user_started_idx
  on public.analytics_sessions (user_id, started_at desc);
create index if not exists analytics_sessions_started_idx
  on public.analytics_sessions (started_at desc);
create index if not exists analytics_events_user_occurred_idx
  on public.analytics_events (user_id, occurred_at desc);
create index if not exists analytics_events_name_occurred_idx
  on public.analytics_events (event_name, occurred_at desc);
create index if not exists analytics_anonymous_daily_date_idx
  on public.analytics_anonymous_daily (bucket_date desc);
create index if not exists analytics_consent_history_user_created_idx
  on public.analytics_consent_history (user_id, created_at desc);

alter table public.analytics_consents enable row level security;
alter table public.analytics_consent_history enable row level security;
alter table public.analytics_sessions enable row level security;
alter table public.analytics_events enable row level security;
alter table public.analytics_anonymous_daily enable row level security;

drop policy if exists analytics_consents_select_own_or_admin on public.analytics_consents;
create policy analytics_consents_select_own_or_admin
  on public.analytics_consents
  for select
  to authenticated
  using (user_id = auth.uid() or public.is_admin());

drop policy if exists analytics_consent_history_select_own_or_admin on public.analytics_consent_history;
create policy analytics_consent_history_select_own_or_admin
  on public.analytics_consent_history
  for select
  to authenticated
  using (user_id = auth.uid() or public.is_admin());

drop policy if exists analytics_sessions_admin_select on public.analytics_sessions;
create policy analytics_sessions_admin_select
  on public.analytics_sessions
  for select
  to authenticated
  using (public.is_admin());

drop policy if exists analytics_events_admin_select on public.analytics_events;
create policy analytics_events_admin_select
  on public.analytics_events
  for select
  to authenticated
  using (public.is_admin());

drop policy if exists analytics_anonymous_daily_admin_select on public.analytics_anonymous_daily;
create policy analytics_anonymous_daily_admin_select
  on public.analytics_anonymous_daily
  for select
  to authenticated
  using (public.is_admin());

create or replace function public.save_analytics_consent(
  requested_acceptance boolean,
  requested_policy_version text
)
returns public.analytics_consents
language plpgsql
security definer
set search_path = public
as $$
declare
  current_user_id uuid := auth.uid();
  normalized_version text := left(trim(coalesce(requested_policy_version, '')), 40);
  saved_consent public.analytics_consents;
begin
  if current_user_id is null then
    raise exception 'Authentication required.';
  end if;

  if normalized_version = '' then
    raise exception 'Policy version is required.';
  end if;

  insert into public.analytics_consents (
    user_id,
    policy_version,
    accepted_at,
    revoked_at,
    updated_at
  )
  values (
    current_user_id,
    normalized_version,
    now(),
    case when requested_acceptance then null else now() end,
    now()
  )
  on conflict (user_id) do update
  set
    policy_version = excluded.policy_version,
    accepted_at = case
      when requested_acceptance then now()
      else public.analytics_consents.accepted_at
    end,
    revoked_at = case when requested_acceptance then null else now() end,
    updated_at = now()
  returning * into saved_consent;

  insert into public.analytics_consent_history (user_id, policy_version, action)
  values (
    current_user_id,
    normalized_version,
    case when requested_acceptance then 'accepted' else 'revoked' end
  );

  return saved_consent;
end;
$$;

revoke all on function public.save_analytics_consent(boolean, text) from public;
grant execute on function public.save_analytics_consent(boolean, text) to authenticated;

create or replace function public.record_anonymous_analytics(
  requested_event_name text,
  requested_path text,
  requested_device_type text,
  requested_os_family text,
  requested_performance_tier text,
  requested_country_code text,
  requested_region text,
  requested_city text,
  requested_referrer_domain text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  normalized_event text := lower(trim(coalesce(requested_event_name, '')));
begin
  if normalized_event not in (
    'visit', 'page_view', 'product_view', 'artisan_view', 'search',
    'filter', 'contact_click', 'signup_started'
  ) then
    raise exception 'Unsupported anonymous analytics event.';
  end if;

  insert into public.analytics_anonymous_daily (
    bucket_date,
    event_name,
    path,
    device_type,
    os_family,
    performance_tier,
    country_code,
    region,
    city,
    referrer_domain,
    total_count,
    updated_at
  )
  values (
    current_date,
    normalized_event,
    left(coalesce(nullif(trim(requested_path), ''), '/'), 240),
    requested_device_type,
    requested_os_family,
    requested_performance_tier,
    left(coalesce(nullif(trim(requested_country_code), ''), 'unknown'), 8),
    left(coalesce(nullif(trim(requested_region), ''), 'unknown'), 100),
    left(coalesce(nullif(trim(requested_city), ''), 'unknown'), 100),
    left(coalesce(nullif(trim(requested_referrer_domain), ''), 'direct'), 120),
    1,
    now()
  )
  on conflict (
    bucket_date,
    event_name,
    path,
    device_type,
    os_family,
    performance_tier,
    country_code,
    region,
    city,
    referrer_domain
  ) do update
  set
    total_count = public.analytics_anonymous_daily.total_count + 1,
    updated_at = now();
end;
$$;

revoke all on function public.record_anonymous_analytics(text, text, text, text, text, text, text, text, text) from public;
grant execute on function public.record_anonymous_analytics(text, text, text, text, text, text, text, text, text) to service_role;

create or replace function public.handle_new_profile_analytics_consent()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  user_metadata jsonb;
  requested_consent boolean := false;
  requested_version text := '';
begin
  select raw_user_meta_data into user_metadata
  from auth.users
  where id = new.id;

  requested_consent := lower(coalesce(user_metadata ->> 'analytics_consent', 'false')) = 'true';
  requested_version := left(trim(coalesce(user_metadata ->> 'analytics_policy_version', '')), 40);

  if requested_consent and requested_version <> '' then
    insert into public.analytics_consents (user_id, policy_version, accepted_at, revoked_at, updated_at)
    values (new.id, requested_version, now(), null, now())
    on conflict (user_id) do update
    set policy_version = excluded.policy_version,
        accepted_at = now(),
        revoked_at = null,
        updated_at = now();

    insert into public.analytics_consent_history (user_id, policy_version, action)
    values (new.id, requested_version, 'accepted');
  end if;

  return new;
end;
$$;

drop trigger if exists on_profile_created_analytics_consent on public.profiles;
create trigger on_profile_created_analytics_consent
after insert on public.profiles
for each row execute function public.handle_new_profile_analytics_consent();

-- The catalog already had account personalization history. Gate those legacy
-- RPCs behind the same explicit consent so they cannot bypass this contract.
create or replace function public.record_catalog_activity_event_v1(
  requested_artisan_id uuid default null,
  requested_category_id uuid default null,
  requested_product_id uuid default null,
  requested_search_term text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_search_term text;
begin
  if auth.uid() is null or not exists (
    select 1
    from public.analytics_consents consent
    where consent.user_id = auth.uid()
      and consent.revoked_at is null
      and consent.policy_version = '2026-07-analytics-v1'
  ) then
    return;
  end if;

  -- Search actions are counted by the new analytics event without retaining
  -- their free-text value. Keep the legacy parameter for API compatibility.
  v_search_term := null;

  if requested_artisan_id is null
    and requested_category_id is null
    and requested_product_id is null
    and v_search_term is null then
    return;
  end if;

  insert into public.catalog_activity_events (
    user_id,
    artisan_id,
    category_id,
    product_id,
    search_term
  )
  values (
    auth.uid(),
    requested_artisan_id,
    requested_category_id,
    requested_product_id,
    v_search_term
  );
end;
$$;

revoke all on function public.record_catalog_activity_event_v1(uuid, uuid, uuid, text) from public;
grant execute on function public.record_catalog_activity_event_v1(uuid, uuid, uuid, text) to authenticated;

create or replace function public.get_catalog_activity_state_v1()
returns table (
  "recentArtisanIds" uuid[],
  "recentCategoryIds" uuid[],
  "recentProductIds" uuid[],
  "recentSearches" text[],
  recent_artisan_ids uuid[],
  recent_category_ids uuid[],
  recent_product_ids uuid[],
  recent_searches text[]
)
language sql
stable
security definer
set search_path = public
as $$
  with active_consent as (
    select 1
    from public.analytics_consents consent
    where consent.user_id = auth.uid()
      and consent.revoked_at is null
      and consent.policy_version = '2026-07-analytics-v1'
  ),
  recent_artisans as (
    select artisan_id, max(created_at) as last_seen_at
    from public.catalog_activity_events
    where user_id = auth.uid()
      and artisan_id is not null
      and exists (select 1 from active_consent)
    group by artisan_id
    order by last_seen_at desc
    limit 6
  ),
  recent_categories as (
    select category_id, max(created_at) as last_seen_at
    from public.catalog_activity_events
    where user_id = auth.uid()
      and category_id is not null
      and exists (select 1 from active_consent)
    group by category_id
    order by last_seen_at desc
    limit 6
  ),
  recent_products as (
    select product_id, max(created_at) as last_seen_at
    from public.catalog_activity_events
    where user_id = auth.uid()
      and product_id is not null
      and exists (select 1 from active_consent)
    group by product_id
    order by last_seen_at desc
    limit 12
  ),
  recent_terms as (
    select search_term, max(created_at) as last_seen_at
    from public.catalog_activity_events
    where user_id = auth.uid()
      and nullif(btrim(coalesce(search_term, ''::text)), ''::text) is not null
      and exists (select 1 from active_consent)
    group by search_term
    order by last_seen_at desc
    limit 6
  ),
  state as (
    select
      coalesce(array_agg(recent_artisans.artisan_id order by recent_artisans.last_seen_at desc), '{}'::uuid[]) as artisan_ids,
      coalesce((select array_agg(category_id order by last_seen_at desc) from recent_categories), '{}'::uuid[]) as category_ids,
      coalesce((select array_agg(product_id order by last_seen_at desc) from recent_products), '{}'::uuid[]) as product_ids,
      coalesce((select array_agg(search_term order by last_seen_at desc) from recent_terms), '{}'::text[]) as searches
    from recent_artisans
  )
  select
    state.artisan_ids as "recentArtisanIds",
    state.category_ids as "recentCategoryIds",
    state.product_ids as "recentProductIds",
    state.searches as "recentSearches",
    state.artisan_ids as recent_artisan_ids,
    state.category_ids as recent_category_ids,
    state.product_ids as recent_product_ids,
    state.searches as recent_searches
  from state;
$$;

revoke all on function public.get_catalog_activity_state_v1() from public;
grant execute on function public.get_catalog_activity_state_v1() to authenticated;

create or replace function public.get_admin_analytics_overview(requested_days integer default 30)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  safe_days integer := least(greatest(coalesce(requested_days, 30), 1), 365);
  period_start timestamptz;
  period_date date;
  result jsonb;
begin
  if not public.is_admin() then
    raise exception 'Admin access required.';
  end if;

  period_start := now() - make_interval(days => safe_days);
  period_date := current_date - (safe_days - 1);

  select jsonb_build_object(
    'periodDays', safe_days,
    'anonymousVisits', coalesce((
      select sum(total_count) from public.analytics_anonymous_daily
      where bucket_date >= period_date and event_name = 'visit'
    ), 0),
    'anonymousPageViews', coalesce((
      select sum(total_count) from public.analytics_anonymous_daily
      where bucket_date >= period_date and event_name = 'page_view'
    ), 0),
    'consentedSessions', (
      select count(*) from public.analytics_sessions where started_at >= period_start
    ),
    'consentedUsers', (
      select count(distinct user_id) from public.analytics_sessions where started_at >= period_start
    ),
    'consentedPageViews', (
      select count(*) from public.analytics_events
      where occurred_at >= period_start and event_name = 'page_view'
    ),
    'averageActiveSeconds', coalesce((
      select round(avg(active_seconds)) from public.analytics_sessions where started_at >= period_start
    ), 0),
    'devices', coalesce((
      with device_totals as (
        select device_type as label, sum(total_count)::bigint as total
        from public.analytics_anonymous_daily
        where bucket_date >= period_date and event_name = 'visit'
        group by device_type
        union all
        select device_type as label, count(*)::bigint as total
        from public.analytics_sessions
        where started_at >= period_start
        group by device_type
      )
      select jsonb_agg(jsonb_build_object('label', label, 'count', total_sum) order by total_sum desc)
      from (select label, sum(total)::bigint as total_sum from device_totals group by label) grouped
    ), '[]'::jsonb),
    'operatingSystems', coalesce((
      with os_totals as (
        select os_family as label, sum(total_count)::bigint as total
        from public.analytics_anonymous_daily
        where bucket_date >= period_date and event_name = 'visit'
        group by os_family
        union all
        select os_family as label, count(*)::bigint as total
        from public.analytics_sessions
        where started_at >= period_start
        group by os_family
      )
      select jsonb_agg(jsonb_build_object('label', label, 'count', total_sum) order by total_sum desc)
      from (select label, sum(total)::bigint as total_sum from os_totals group by label) grouped
    ), '[]'::jsonb),
    'performanceTiers', coalesce((
      with tier_totals as (
        select performance_tier as label, sum(total_count)::bigint as total
        from public.analytics_anonymous_daily
        where bucket_date >= period_date and event_name = 'visit'
        group by performance_tier
        union all
        select performance_tier as label, count(*)::bigint as total
        from public.analytics_sessions
        where started_at >= period_start
        group by performance_tier
      )
      select jsonb_agg(jsonb_build_object('label', label, 'count', total_sum) order by total_sum desc)
      from (select label, sum(total)::bigint as total_sum from tier_totals group by label) grouped
    ), '[]'::jsonb),
    'locations', coalesce((
      with location_totals as (
        select city, region, country_code, sum(total_count)::bigint as total
        from public.analytics_anonymous_daily
        where bucket_date >= period_date and event_name = 'visit'
        group by city, region, country_code
        union all
        select city, region, country_code, count(*)::bigint as total
        from public.analytics_sessions
        where started_at >= period_start
        group by city, region, country_code
      )
      select jsonb_agg(jsonb_build_object(
        'city', city,
        'region', region,
        'countryCode', country_code,
        'count', total_sum
      ) order by total_sum desc)
      from (
        select city, region, country_code, sum(total)::bigint as total_sum
        from location_totals
        group by city, region, country_code
        order by total_sum desc
        limit 12
      ) grouped
    ), '[]'::jsonb),
    'topPages', coalesce((
      with page_totals as (
        select path, sum(total_count)::bigint as total
        from public.analytics_anonymous_daily
        where bucket_date >= period_date and event_name = 'page_view'
        group by path
        union all
        select path, count(*)::bigint as total
        from public.analytics_events
        where occurred_at >= period_start and event_name = 'page_view'
        group by path
      )
      select jsonb_agg(jsonb_build_object('path', path, 'count', total_sum) order by total_sum desc)
      from (
        select path, sum(total)::bigint as total_sum
        from page_totals
        group by path
        order by total_sum desc
        limit 12
      ) grouped
    ), '[]'::jsonb),
    'topEvents', coalesce((
      select jsonb_agg(jsonb_build_object('label', event_name, 'count', total) order by total desc)
      from (
        select event_name, count(*)::bigint as total
        from public.analytics_events
        where occurred_at >= period_start
        group by event_name
        order by total desc
        limit 12
      ) grouped
    ), '[]'::jsonb),
    'recentUsers', coalesce((
      select jsonb_agg(jsonb_build_object(
        'userId', grouped.user_id,
        'fullName', grouped.full_name,
        'email', grouped.email,
        'role', grouped.role,
        'sessions', grouped.sessions,
        'events', grouped.events,
        'lastSeenAt', grouped.last_seen_at
      ) order by grouped.last_seen_at desc)
      from (
        select
          profiles.id as user_id,
          profiles.full_name,
          profiles.email,
          profiles.role,
          count(distinct sessions.id)::bigint as sessions,
          count(events.id)::bigint as events,
          max(sessions.last_seen_at) as last_seen_at
        from public.analytics_sessions sessions
        join public.profiles profiles on profiles.id = sessions.user_id
        left join public.analytics_events events on events.session_id = sessions.id
        where sessions.started_at >= period_start
        group by profiles.id, profiles.full_name, profiles.email, profiles.role
        order by last_seen_at desc
        limit 20
      ) grouped
    ), '[]'::jsonb)
  ) into result;

  return result;
end;
$$;

revoke all on function public.get_admin_analytics_overview(integer) from public;
grant execute on function public.get_admin_analytics_overview(integer) to authenticated;

create or replace function public.get_admin_analytics_user_history(
  requested_user_id uuid,
  requested_limit integer default 50
)
returns table (
  event_name text,
  path text,
  entity_type text,
  entity_id uuid,
  occurred_at timestamptz,
  device_type text,
  os_family text,
  performance_tier text,
  city text,
  region text,
  country_code text
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'Admin access required.';
  end if;

  return query
  select
    events.event_name,
    events.path,
    events.entity_type,
    events.entity_id,
    events.occurred_at,
    sessions.device_type,
    sessions.os_family,
    sessions.performance_tier,
    sessions.city,
    sessions.region,
    sessions.country_code
  from public.analytics_events events
  join public.analytics_sessions sessions on sessions.id = events.session_id
  where events.user_id = requested_user_id
  order by events.occurred_at desc
  limit least(greatest(coalesce(requested_limit, 50), 1), 200);
end;
$$;

revoke all on function public.get_admin_analytics_user_history(uuid, integer) from public;
grant execute on function public.get_admin_analytics_user_history(uuid, integer) to authenticated;

create or replace function public.cleanup_internal_analytics()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  delete from public.analytics_events where occurred_at < now() - interval '365 days';
  delete from public.analytics_sessions where started_at < now() - interval '365 days';
  delete from public.analytics_anonymous_daily where bucket_date < current_date - 730;
end;
$$;

revoke all on function public.cleanup_internal_analytics() from public;
grant execute on function public.cleanup_internal_analytics() to service_role;
